FROM dickmao/scipy-gpu

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    nfs-common && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# Install Tensorflow
RUN pip install --quiet --no-cache-dir \
    'git+https://github.com/dickmao/Kaggler.git@5d415ae15c7a71327a4700cc0dbdadc523234209' && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
