FROM dickmao/scipy-gpu

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    nfs-common && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# Install Tensorflow
RUN pip install --quiet --no-cache-dir \
    'git+https://github.com/dickmao/Kaggler.git@4432ba40a3b63890e3109d53fedfbcfb17aa495f' && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
