FROM dickmao/scipy-gpu

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    nfs-common && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# Install Tensorflow
RUN pip install --quiet --no-cache-dir \
    'git+https://github.com/dickmao/Kaggler.git@9d48393d332515efa29d0b1851845564ce72de5c' && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
