name: CI

on:
  pull_request:
    paths-ignore:
    - '**.rst'
  push:
    paths-ignore:
    - '**.rst'
    branches-ignore:
    - 'master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
        go-version: [1.15.1]

    steps:
    - uses: actions/checkout@v2

    - name: golang ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-001

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-001

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.local
        key: ${{ runner.os }}-local-001

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: |
          /usr/local/lib/pkgconfig/libgit2**
          /usr/local/lib/libgit2**
          /usr/local/include/git2**
        key: ${{ runner.os }}-libgit2-003

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: |
          /usr/local/Cellar/pkg-config/**
          /usr/bin/pkg-config
          /usr/local/bin/pkg-config
        key: ${{ runner.os }}-pkgconfig-000

    - name: paths
      uses: dickmao/setup-paths@master
      with:
        paths: local/bin

    - name: apt-get
      if: startsWith(runner.os, 'Linux')
      run: |
        sudo apt-get -yq update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install gnutls-bin

    - name: pkgconfig
      if: startsWith(runner.os, 'macOS')
      run: |
         brew list pkgconfig &>/dev/null || HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config

    - name: versions
      run: |
        go version
        curl --version

    - name: libgit2-Linux
      if: startsWith(runner.os, 'Linux')
      run: |
         cd $GITHUB_WORKSPACE
         LD_LIBRARY_PATH=~/.local/lib PKG_CONFIG_PATH=~/.local/lib/pkgconfig make test

    - name: libgit2-macOS
      if: startsWith(runner.os, 'macOS')
      run: |
         cd $GITHUB_WORKSPACE
         make test
